apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: node:21-alpine
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args:
          - |
            npm install && npm run dev
        ports:
        - containerPort: 5173

