apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  # NOTE: depending on which version of the book you have, this may say port 9999. The latest version of the book uses 8888 to match the pod.
  ports:
  - port: 5173
    targetPort: 5173
  selector:
    app: client
  type: ClusterIP