version: '3.7'

services:
  laravel:
    networks:
      - sd
    image: cesar02dd/server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    container_name: server

  react:
    networks:
      - sd
    image: cesar02dd/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    depends_on:
      - laravel
    container_name: client

  database:
    networks:
      - sd
    image: cesar02dd/mysql:latest
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sd
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - data:/var/lib/mysql

volumes:
  data:

networks:
  sd:
    driver: bridge

 
 