version: '3.7'

services:
  react:
    networks:
      - app
    image: node:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 3000:5173
    
  database:
    networks:
      - app
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sd
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 

networks:
  app:
    driver: bridge

 