apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      
  name: laravel
      image: server:latest
      ports:
containerPort: 80
    env:
name: DB_HOST
    value: mysql-service
name: DB_PORT
  value: "3306"
name: DB_DATABASE
valueFrom:
  secretKeyRef:
    name: mysql-secret
    key: mysql-database
name: DB_USERNAME
valueFrom:
  secretKeyRef:
    name: mysql-secret
    key: mysql-user
name: DB_PASSWORD
valueFrom:
  secretKeyRef:
    name: mysql-secret
    key: mysql-password