apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: sge
  labels:
    app: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30008