apiVersion: v1
kind: Service
metadata:
  name: reactvite
  namespace: sge
  labels:
    app: reactvite
spec:
  # NOTE: depending on which version of the book you have, this may say port 9999. The latest version of the book uses 8888 to match the pod.
  ports:
  - port: 5173
  selector:
    app: reactvite
  type: ClusterIP